config/routes.rb
Rails.application.routes.draw do

  get 'bookings/index'
  # all the 7 lines below were replaces with a simple 'resources :rides' line above. Keeping it DRY.
  # get 'rides/index'
  # get 'rides/show'
  # get 'rides/new'
  # get 'rides/edit'
  # get 'rides/create'
  # get 'rides/update'
  # get 'rides/destroy'
  # get 'welcome/index'
  resources :rides
  post 'rides/create'
  get 'rides/error'

  devise_for :users
  
  resources :bookings

  get "/", to: "welcome#index", as: "root"
  get 'welcome/index'

  get "/payments/success", to: "payments#success"

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :ride
end

app/models/ride.rb
class Ride < ApplicationRecord
  belongs_to :user
  validates :ride_date, :ride_time, :price, presence: true
  has_many :bookings
  has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, :phone_number, presence: true
  validates :phone_number, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }
  has_many :rides
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @bookings = current_user.bookings
    @rides = current_user.rides.joins(:bookings)
  
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def success
    @ride = Ride.find(params["rideId"])
    @booking = current_user.bookings.create(ride_id: @ride.id)

  end

end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_user_ride, only: [ :edit, :update, :destroy ]


  def index
    @rides = Ride.all # returns an array of rides
  end

  def error
  end


  def show
    if Ride.find_by(id: params[:id])
      @ride = Ride.find_by(id: params[:id])  
      @ride_time = @ride.ride_time.strftime("%H:%M")
      session = Stripe::Checkout::Session.create(
          payment_method_types: ['card'],
          customer_email: current_user.email,
          line_items: [{
              name: @ride.user_id,
              description: "ride from: " + @ride.departure_city + "ride to: " + @ride.arrival_city,
              amount: (@ride.price * 100).to_i,
              currency: 'aud',
              quantity: 1,
          }],
          payment_intent_data: {
              metadata: {
                  user_id: current_user.id,
                  ride_id: @ride.id
              }
          },
          success_url: "#{root_url}payments/success?userId=#{current_user.id}&rideId=#{@ride.id}",
          cancel_url: "#{root_url}rides"
      )
      @session_id = session.id

    else
      render rides_error_path
    end
  end

  def new
    @ride = Ride.new
  end

  def edit
    @ride = Ride.find(params[:id])
  end

  def create
    @ride = Ride.new(ride_params)
    @ride.user_id = current_user.id

    if @ride.save 
      redirect_to @ride 
    else 
      render :new 
     end 
  end

  def update
    @ride = Ride.find(params[:id])
    
    if @ride.update( ride_params )
      redirect_to @ride
    else
      render :edit
    end
  end

  def destroy
    @ride = Ride.find(params[:id])
    @ride.destroy
    redirect_to rides_path
  end


  private

  def ride_params
    ride_params = params.require(:ride).permit(:user_id, :departure_city, :arrival_city, :meeting_point, :ride_date, :ride_time, :car_color, :car_make, :price, :picture )
  end

  def set_user_ride
    id = params[:id]
    @ride = current_user.rides.find_by_id(id)

    if @ride == nil
      redirect_to rides_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookings/index.html.erb
<h1>My Bookings </h1>

<h3>Rides that you bought</h3>
<table>
    <tr>
        <th>Booked by</th>
        <th>Ride ID</th>
        <th>Departure City</th>
        <th>Arrival City</th>
        <th>Driver Name</th>
        <th>Driver Phone Number</th>
    </tr>    


<% @bookings.each do |booking| %>
<tr>
    <td><%= booking.user.name %></td>
    <td><%= booking.ride_id %></td>
    <td><%= booking.ride.departure_city %></td>
    <td><%= booking.ride.arrival_city %></td>
    <td><%= booking.ride.user.name %></td>
    <td><%= booking.ride.user.phone_number %></td>
</tr>
<% end %>
</table>

<br>
-------------

<h3>Rides that you sold</h3>

<table>
    <tr>
        <th>Booked by</th>
        <th>Phone number of passanger</th>
        <th>Ride ID</th>
        <th>Departure City</th>
        <th>Arrival City</th>
    </tr>    

<% @rides.each do |ride| %>
  <% ride.bookings.each do |booking|%>
  <tr>
        <td><%= booking.user.name %></td>
        <td><%= booking.user.phone_number %></td>
    <% end %>

    <td><%= ride.id %></td>
    <td><%= ride.departure_city %></td>
    <td><%= ride.arrival_city %></td>
</tr>
<% end %>

</table>

<br>
<%= link_to "Back to all rides", rides_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HitchARide</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <% if user_signed_in? %>
      <p>Hi there you are currently signed in as "<%= current_user.name%>"</p>
      <%= link_to "logout", destroy_user_session_path, method: :delete %>
      
    <% else %>
      <%= link_to "login", new_user_session_path %>
    <% end %>

    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/payments/success.html.erb
<p>You've successfully made a payment! </p>

<p> You paid: <%= @ride.price %> AUD</p>
<p> Your ride is on the : <%= @ride.ride_date %></p>
<p> Ride time: <%= @ride.ride_time.strftime("%H:%M")  %></p>
<p> Departure City: <%= @ride.departure_city %></p>
<p> Arrival City: <%= @ride.arrival_city %></p>
<p> Meeting Point: <%= @ride.meeting_point %></p>
<p> Name of your driver: <%= @ride.user.name %></p>
<p> Phone Number of your driver: <%= @ride.user.phone_number %></p>


<%= link_to "Go To Rides", rides_path%>

app/views/rides/_form.html.erb
<%= form_with model: ride, local: true do |form| %>
    <% if ride.errors.any? %>
        <div id="error_explanation">
            <ul>
                <% ride.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

  
    <div>
        <%= form.label :departure_city %>
        <%= form.select(:departure_city, [ ['Adelaide'], ['Perth'], ['Darwin'], ['Brisbane'], ['Sydney'],['Melbourne'], ['Ballarat'], ['Bendigo'] ].sort )%>
    </div>
    <div>
        <%= form.label :arrival_city %>
        <%= form.select(:arrival_city, [ ['Adelaide'], ['Perth'], ['Darwin'], ['Brisbane'], ['Sydney'],['Melbourne'], ['Ballarat'], ['Bendigo'] ].sort )%>
    </div>
    <div>
        <%= form.label :meeting_point %>
        <%= form.text_area :meeting_point %>
    </div>
    <div>
        <%= form.label :ride_date %>
        <%= form.date_field :ride_date%>
    </div>
    <div>
        <%= form.label :ride_time %>
        <%= form.time_field :ride_time %>
    </div>

    <div>
        <%= form.label :car_color %>
        <%= form.select(:car_color, [['blue'], ['red'], ['green'], ['yellow'], ['pink'], ['orange'], ['white'], ['black'], ['grey'], ['purple']].sort )%>
    </div>

    <div>
        <%= form.label :car_make %>
        <%= form.select(:car_make, [['Toyota'], ['Mercedes'], ['VW'], ['Porsche'], ['Subaru'], ['Holden'], ['Nissan'], ['Honda'], ['Hyundai'], ['Ford'], ['Mazda'], ['Mitsubishi'], ['Audi'], ['Kia'], ['Jeep'] ].sort )%>
    </div>

    <div>
        <%= form.label :price %>
        <%= form.number_field :price %>
    </div>

    <div>
        <%= form.label :car_picture %> <%= form.file_field :picture, accept:'image/png,image/gif,image/jpeg,image/jpg' %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/rides/edit.html.erb
<h1> Edit Ride</h1>

<%= render 'form', ride: @ride%>

app/views/rides/error.erb
<h1>These aren't the rides you're looking for.</h1>

<%= link_to "Back to all the rides", rides_path%>

app/views/rides/index.html.erb
<h1>Browse all the available rides in Australia </h1>

<h1>These are the rides that other people listed</h1>
<table>
    <tr>
        <th>Departure City</th>
        <th>Arrival City</th>
        <th>Meeting Point</th>
        <th>Departure Date</th>
        <th>Departure Time</th>
        <th>Price</th>
    </tr>    

    <% @rides.each do |ride| %>
        <% if (current_user && current_user.id != ride.user_id) || !current_user %>
            <tr>
                <td><%= ride.departure_city %></td>
                <td><%= ride.arrival_city %></td>
                <td><%= ride.meeting_point %></td>
                <td><%= ride.ride_date %></td>
                <td><%= ride.ride_time.strftime("%H:%M") %></td>
                <td><%= ride.price %></td>

                <td><%= link_to "Show", ride_path( ride)%></td>  
                
            </tr>    
        <%end%>
    <% end%>

</table>

-------
<%if (current_user)%>

    <h1>These are the rides that you listed</h1>

    <table>
        <tr>
            <th>Departure City</th>
            <th>Arrival City</th>
            <th>Meeting Point</th>
            <th>Departure Date</th>
            <th>Departure Time</th>
            <th>Price</th>
        </tr>    

        <% @rides.each do |ride| %>
    
        <% if current_user.id == ride.user_id%>
            <tr>
                <td><%= ride.departure_city %></td>
                <td><%= ride.arrival_city %></td>
                <td><%= ride.meeting_point %></td>
                <td><%= ride.ride_date %></td>
                <td><%= ride.ride_time.strftime("%H:%M") %></td>
                <td><%= ride.price %></td>

                <td><%= link_to "Show", ride_path( ride)%></td>  
                <td><%= link_to "Edit", edit_ride_path( ride ) %></td>
                <td><%= link_to "Destroy", ride_path( ride ), method: :delete, data: { confirm: "Are you really sure?"} %></td> 
            </tr>    
        <%end%>
        <%end%>
    
<% end %>

    


</table>

-------------

<br>

<%= link_to "Add New Ride", new_ride_path%>
<br>
<%= link_to "Bookings", bookings_path%>

app/views/rides/new.html.erb
<h1> New Ride</h1>

<%= render 'form', ride: @ride%>

app/views/rides/show.html.erb
<h1><%= "This is the ride:" %></h1>

<div>
    <%= image_tag(@ride.picture ,size:200)if @ride.picture.attached?%>
</div>

<p>
    <strong>Departure City:</strong>
    <%= @ride.departure_city %>
</p>

<p>
    <strong>Arrival City:</strong>
    <%= @ride.arrival_city %>
</p>

<p>
    <strong>Meeting Point:</strong>
    <%= @ride.meeting_point%>
</p>

<p>
    <strong>Date:</strong>
    <%= @ride.ride_date%>
</p>

<p>
    <strong>Time:</strong>
    <%= @ride_time%>
</p>


<p>
    <strong>Driver Name:</strong>
    <%= @ride.user.name %>
</p>

<p>
    <strong>Car Color:</strong>
    <%= @ride.car_color%>
</p>

<p>
    <strong>Car Make:</strong>
    <%= @ride.car_make%>
</p>

<p>
    <strong>Price:</strong>
    <%= @ride.price%>
</p>




<button data-stripe="payment">
  Pay For the Ride <%= number_to_currency(@ride.price) %>
</button>

<script src="https://js.stripe.com/v3/"></script>

<script>
  document
    .querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      );

      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      });
    });
</script>

<%= link_to "Back to all rides", rides_path %>
<%if (current_user)%>
<% if current_user.id == @ride.user_id%>
    <td><%= link_to "Edit", edit_ride_path( @ride ) %></td>
    <td><%= link_to "Destroy", ride_path( @ride ), method: :delete, data: { confirm: "Are you really sure?"} %></td>
<%end%>
<%end%>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to HitchARide2.com</h1>

<%= link_to "View all the Rides", rides_path%>